name: with @swc/core@latest

on:
    schedule:
        - cron: "0 0,12 * * *"

env:
    CARGO_INCREMENTAL: 0
    RUST_LOG: "debug"
    DIFF: 0
    RUST_MIN_STACK: 4194304
    NODE_ENV: "development"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  target: wasm32-wasi

            - name: Cache cargo registry
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      .cargo-cache/
                      target
                  key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

            - run: cargo build --target wasm32-wasi

            - uses: pnpm/action-setup@v2.2.4
            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"

            - run: pnpm add -D --ignore-scripts @swc/core@latest @swc/jest@latest
            - run: pnpm test:debug
