name: Test

on: [push, pull_request]

env:
    CARGO_INCREMENTAL: 0
    RUST_LOG: "debug"
    DIFF: 0
    RUST_MIN_STACK: 4194304
    NODE_ENV: "development"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  target: wasm32-unknown-unknown

            - name: Cache cargo registry
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      .cargo-cache/
                      target
                  key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

            - name: Run cargo check for all targets
              run: cargo check --color always --all --all-targets

            - run: cargo test

            # test in node
            - uses: pnpm/action-setup@v2.2.4
            - uses: actions/setup-node@v3
              with:
                  node-version-file: ".node-version"
                  cache: "pnpm"

            - run: pnpm i --ignore-scripts --frozen-lockfile
            - run: pnpm test:debug
